// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Column = {
    comment?: string | null;
    data_type: PostgresDataType;
    default_value?: string | null;
    is_nullable: boolean;
    name: string;
};

export type Constraint = {
    columns: Array<string>;
    constraint_type: ConstraintType;
    name: string;
};

export type ConstraintType = {
    type: 'PrimaryKey';
} | {
    type: 'Unique';
} | {
    data: string;
    type: 'Check';
} | {
    data: {
        foreign_columns: Array<string>;
        foreign_schema: string;
        foreign_table: string;
        on_delete: ReferentialAction;
        on_update: ReferentialAction;
    };
    type: 'ForeignKey';
};

export type Database = {
    name: string;
    schemas: Array<Schema>;
};

export type EnumType = {
    name: string;
    oid: number;
    schema_name: string;
    variants: Array<string>;
};

export type Function = {
    argument_types: Array<string>;
    definition: string;
    is_procedure: boolean;
    language: string;
    name: string;
    oid: number;
    return_type: string;
    schema_name: string;
};

export type Index = {
    columns: Array<string>;
    definition: string;
    index_type: string;
    is_primary_key: boolean;
    is_unique: boolean;
    name: string;
    partial_condition?: string | null;
};

export type PostgresDataType = {
    type: 'Boolean';
} | {
    type: 'SmallInt';
} | {
    type: 'Integer';
} | {
    type: 'BigInt';
} | {
    type: 'Real';
} | {
    type: 'DoublePrecision';
} | {
    data: {
        precision?: number | null;
        scale?: number | null;
    };
    type: 'Numeric';
} | {
    data: {
        length?: number | null;
    };
    type: 'Character';
} | {
    data: {
        length?: number | null;
    };
    type: 'Varchar';
} | {
    type: 'Text';
} | {
    type: 'Bytea';
} | {
    type: 'Date';
} | {
    data: {
        with_time_zone: boolean;
    };
    type: 'Timestamp';
} | {
    data: {
        with_time_zone: boolean;
    };
    type: 'Time';
} | {
    type: 'Interval';
} | {
    type: 'Json';
} | {
    type: 'Jsonb';
} | {
    type: 'Uuid';
} | {
    type: 'Inet';
} | {
    type: 'Cidr';
} | {
    type: 'MacAddr';
} | {
    data: {
        element_type: PostgresDataType;
    };
    type: 'Array';
} | {
    data: {
        name: string;
    };
    type: 'Custom';
};

export type ReferentialAction = 'NoAction' | 'Restrict' | 'Cascade' | 'SetNull' | 'SetDefault';

export type ScanRequest = {
    db_url: string;
};

export type ScanResponse = Database;

export type Schema = {
    enums: Array<EnumType>;
    functions: Array<Function>;
    name: string;
    oid: number;
    sequences: Array<Sequence>;
    tables: Array<Table>;
    views: Array<View>;
};

export type Sequence = {
    cycle: boolean;
    increment_by: number;
    max_value: number;
    min_value: number;
    name: string;
    oid: number;
    schema_name: string;
    start_value: number;
};

export type Table = {
    columns: Array<Column>;
    comment?: string | null;
    constraints: Array<Constraint>;
    indexes: Array<Index>;
    name: string;
    oid: number;
    schema_name: string;
    triggers: Array<Trigger>;
};

export type Trigger = {
    action_condition?: string | null;
    action_statement: string;
    action_timing: string;
    event_manipulation: string;
    name: string;
};

export type View = {
    definition: string;
    is_updatable: boolean;
    name: string;
    oid: number;
    schema_name: string;
};

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckResponses = {
    /**
     * Health check
     */
    200: string;
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];

export type ScanDatabaseData = {
    body: ScanRequest;
    path?: never;
    query?: never;
    url: '/scan';
};

export type ScanDatabaseErrors = {
    /**
     * Invalid request or connection error
     */
    400: string;
    /**
     * Scanner error
     */
    500: string;
};

export type ScanDatabaseError = ScanDatabaseErrors[keyof ScanDatabaseErrors];

export type ScanDatabaseResponses = {
    /**
     * Database scan result
     */
    200: Database;
};

export type ScanDatabaseResponse = ScanDatabaseResponses[keyof ScanDatabaseResponses];
