/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppDatabasesNewRouteImport } from './routes/app/databases/new'
import { Route as AppDatabasesDbIdSchemaRouteImport } from './routes/app/databases/$dbId.schema'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDatabasesNewRoute = AppDatabasesNewRouteImport.update({
  id: '/databases/new',
  path: '/databases/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDatabasesDbIdSchemaRoute = AppDatabasesDbIdSchemaRouteImport.update({
  id: '/databases/$dbId/schema',
  path: '/databases/$dbId/schema',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/app/': typeof AppIndexRoute
  '/app/databases/new': typeof AppDatabasesNewRoute
  '/app/databases/$dbId/schema': typeof AppDatabasesDbIdSchemaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppIndexRoute
  '/app/databases/new': typeof AppDatabasesNewRoute
  '/app/databases/$dbId/schema': typeof AppDatabasesDbIdSchemaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/app/': typeof AppIndexRoute
  '/app/databases/new': typeof AppDatabasesNewRoute
  '/app/databases/$dbId/schema': typeof AppDatabasesDbIdSchemaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/about'
    | '/app/'
    | '/app/databases/new'
    | '/app/databases/$dbId/schema'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app'
    | '/app/databases/new'
    | '/app/databases/$dbId/schema'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/about'
    | '/app/'
    | '/app/databases/new'
    | '/app/databases/$dbId/schema'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/databases/new': {
      id: '/app/databases/new'
      path: '/databases/new'
      fullPath: '/app/databases/new'
      preLoaderRoute: typeof AppDatabasesNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/databases/$dbId/schema': {
      id: '/app/databases/$dbId/schema'
      path: '/databases/$dbId/schema'
      fullPath: '/app/databases/$dbId/schema'
      preLoaderRoute: typeof AppDatabasesDbIdSchemaRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppDatabasesNewRoute: typeof AppDatabasesNewRoute
  AppDatabasesDbIdSchemaRoute: typeof AppDatabasesDbIdSchemaRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppDatabasesNewRoute: AppDatabasesNewRoute,
  AppDatabasesDbIdSchemaRoute: AppDatabasesDbIdSchemaRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
